# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Unix-Installer

on:
  push:
  pull_request:
    types:
      - opened
      - edited

jobs:
  installation_test:
    name: samora-lang installation test.
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo sh ./Unix/installer.sh
      - run: samora --help
  installation_win_test:
    name: samora-lang win installation test. 
    runs-on: ubuntu-latest
    steps:
      - name: check-win-installer 
        shell: pwsh
        run: ls  
      - name: win-installer 
        shell: pwsh
        run: ./Windows/installer.ps1 
